#!/bin/bash

export VAGRANT_CWD=/Users/brandonbarrow/dev/brandonlbarrow/podman

ACTION=$1

case $ACTION in
  "down")
    echo "Shutting down podman"
    vagrant halt
    ;;

  "up")
    echo "STARTING podman"
    vagrant up
    ;;

esac
